# Generated by Django 3.2.3 on 2022-01-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(blank=True, to='backend.Item'),
        ),
    ]
