# Generated by Django 3.2.3 on 2022-01-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-score', '-red', '-blue', '-green']},
        ),
    ]
